[package]
name = "espeak-py"
version = "0.1.0"
authors = ["Benjamin Levin <ben@poly-ai.com>"]
edition = "2018"
description = "Python bindings for a very narrow subset of espeak"

[dependencies]
espeak-sys = { path = "../espeak-sys" }
