[build-system]
requires = ["maturin>=0.10,<0.11"]
build-backend = "maturin"

[project]
name = "espeak_py"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust"
]
license = { file = "LICENSE" }
